### ISSUE TITLE
Cannot use tool

### ISSUE THREAD

**Issue by ghost** [sidsukana/QSpellWork#4]
Greetings, I download your tools but i'm having a problem, I cannot find any spells (or use it for that matter)

http://i.imgur.com/y2yhWBP.png

I edited plugins for 1.12.x & 2.4.3
http://i.imgur.com/tfUz8HU.png I pointed the dbc path to my path ( it doesn't show it here but in QSW.ini the path is saved).

althought I do have an error in debug.log which is 

[0819/174833:ERROR:resource_bundle.cc(720)] Failed to load C:\Users\Dany\Desktop\qsw\resources\qtwebengine_devtools_resources.pak
Some features may not be available.

**Comment by sidsukana** [comment]
@Blumfield
Check again:
1. Try load plugin (you receive message to set settings)
2. Set settings (you settings look right)
3. Try load this plugin again

**Comment by ghost** [comment]
Hi, still the same problem

**Comment by sidsukana** [comment]
[0819/174833:ERROR:resource_bundle.cc(720)] Failed to load C:\Users\Dany\Desktop\qsw\resources\qtwebengine_devtools_resources.pak
This error does not affect the qsw.
Now i use new installed Windows 10 without Qt libraries, download QSW_2.0.0.7z and run with previous steps.

You can not load one of the plugins, or both?

**Comment by sidsukana** [comment]
Look https://youtu.be/0KaCccgwyzI

**Comment by ghost** [comment]
I followed your video and it worked thanks a lots

**Comment by sidsukana** [comment]
@Blumfield if you want setup other lugin, repeat these steps.

In the future, I plan to make the indication of the active plug-in, as well as add a plug-in by default when you start the program
