### ISSUE TITLE
No spell icons?

### ISSUE THREAD

**Issue by Phatcat** [sidsukana/QSpellWork#5]
Spell icons don't seem to work for me on the 2.0 version. I can't seem to see any spell icons at all.

**Comment by sidsukana** [comment]
I removed  icons preload from wowhead site. To display the icon, you need to configure QSW work directly with the game client

**Comment by Phatcat** [comment]
Alright, didn't know the icons were loaded from wowhead. I guess this is no issue then and can be closed :+1:
