### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by gemt** [sidsukana/QSpellWork#7]
I can't find any information about licensing in QSpellWork. I have recently been playing around with integrating parts of the code in another tool I'm working on (you can check it out on my github, https://github.com/gemt/CreatureScripter, huge mess, complete wip), and was wondering, before I go too far down this path, what you would allow/not allow in terms of re-using QSpellWork in this manner.

**Comment by sidsukana** [comment]
@gemt Hello, i added license file (i prefer MIT)
